name: Build

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:

jobs:
  build:
    name: Build (${{ matrix.node-version }}) on ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [ 20.x, 22.x, 24.x, 25.x, lts/* ]
        os: [ ubuntu-latest ]
        include:
          - node-version: lts/*
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint package
        run: pnpm --recursive --stream lint

      - name: Test package
        run: pnpm --recursive --stream test

      - name: Package
        if: matrix.node-version == 'lts/*' && matrix.os == 'ubuntu-latest'
        run: pnpm pack

      - name: Upload build artifacts
        uses: actions/upload-artifact@v6
        if: matrix.node-version == 'lts/*' && matrix.os == 'ubuntu-latest'
        with:
          name: lingui-react-router
          path: lingui-react-router*.tgz
          retention-days: 7

  build-min-supported:
    name: Build (Minimal Supported)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v6
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Override versions
        uses: actions/github-script@v8
        with:
          #language=js
          script: |
            const fs = require("fs")
            const pkg = JSON.parse(fs.readFileSync("package.json", "utf8"))
            const linguiVersion = pkg.peerDependencies["@lingui/core"].replace("^", "")
            const reactVersion = pkg.peerDependencies["react"].replace("^", "")
            const reactRouterVersion = pkg.peerDependencies["react-router"].replace("^", "")

            pkg.pnpm.overrides = {
              ...(pkg.pnpm.overrides || {}),
              "@lingui/cli": linguiVersion,
              "@lingui/conf": linguiVersion,
              "@lingui/core": linguiVersion,
              "@lingui/react": linguiVersion,
              "@lingui/vite-plugin": linguiVersion,
              "@react-router/dev": reactRouterVersion,
              "@react-router/node": reactRouterVersion,
              "@react-router/serve": reactRouterVersion,
              "@react-router/express": reactRouterVersion,
              "react-router": reactRouterVersion,
              "react": reactVersion,
              "react-dom": reactVersion,
            }
            fs.writeFileSync("package.json", JSON.stringify(pkg, null, 2) + "\n")
            fs.rmSync("pnpm-lock.yaml", { force: true })

      - name: Install dependencies with minimal versions
        run: pnpm install --no-frozen-lockfile

      - name: Test with minimal versions
        run: pnpm test:all

  build-all:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: [ build, build-min-supported ]
    steps:
      - run: echo OK

  publish:
    name: Publish
    runs-on: ubuntu-latest
    environment: publish
    needs: build-all
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          registry-url: https://registry.npmjs.org/
          node-version: lts/*

      - name: Update npm
        run: npm install -g npm

      - name: Download build artifacts
        uses: actions/download-artifact@v7
        with:
          name: lingui-react-router

      - name: Publish package
        run: npm publish lingui-react-router*.tgz
